#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")
#@ load("/lib/cmake.lib.yml", "cmake", "cmake_release_base_configuration")

#@ source_url = "https://github.com/google/benchmark/archive/refs/tags/v1.9.0.tar.gz"

#@yaml/text-templated-strings
---
#@ def args():
license: LICENSE
configure: |
  mkdir -p "$BUILD_DIR"
  extract.sh --into "$BUILD_DIR" "(@= source_url @)"
  cd "$BUILD_DIR"
  
  (@= cmake @) \
    (@= cmake_release_base_configuration @) \
    -DBUILD_SHARED_LIBS=ON \
    -DBENCHMARK_INSTALL_DOCS=OFF \
    -DBENCHMARK_ENABLE_TESTING=OFF \
    -DBENCHMARK_DOWNLOAD_DEPENDENCIES=OFF
build_system: make
build_dependencies:
  - host-cxx-toolchain
dependencies:
  - host-libcxx
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  google-benchmark: #@ single_build_component(**args())
