#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("/lib/create-component.lib.yml", "single_build_component")
#@ load("/lib/make.lib.yml", "make")
#@ load("/lib/util.lib.yml", "datavalue")

#@ source_url = "https://ftp.gnu.org/gnu/gcc/gcc-" + str(datavalue("gcc_host_version")) + "/gcc-" + str(datavalue("gcc_host_version")) + ".tar.gz"

#@yaml/text-templated-strings
---
#@ def args():
license: source/COPYING
configure: |
  mkdir -p "$BUILD_DIR/source"
  extract.sh --into "$BUILD_DIR/source" (@= source_url @)

  cd "$BUILD_DIR"
  ./source/configure \
    --prefix="$INSTALL_LINK_ONLY_PATH" \
    --disable-multilib \
    --enable-languages=c \
    --disable-nls \
    --disable-libsanitizer \
    --with-glibc-version=2.13 \
    --with-gmp="$ORCHESTRA_ROOT" \
    --with-mpfr="$ORCHESTRA_ROOT" \
    --with-mpc="$ORCHESTRA_ROOT"
install: |
  cd "$BUILD_DIR"
  (@= make @) all-gcc
  (@= make @) all-target-libgcc
  (@= make @) install-target-libgcc
  cp -a "${DESTDIR}${INSTALL_LINK_ONLY_PATH}"/lib/gcc/x86_64-pc-linux-gnu/(@= str(datavalue("gcc_host_version")) @)/*.{a,o} "${DESTDIR}${INSTALL_LINK_ONLY_PATH}"/lib/

  mkdir -p "${DESTDIR}${INSTALL_LINK_ONLY_PATH}"/include/
  cp -a "${DESTDIR}${INSTALL_LINK_ONLY_PATH}"/lib/gcc/x86_64-pc-linux-gnu/(@= str(datavalue("gcc_host_version")) @)/include/* "${DESTDIR}${INSTALL_LINK_ONLY_PATH}"/include/
build_dependencies:
  - toolchain/host/linux-headers
  - gmp
  - mpc
  - mpfr
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  libgcc: #@ single_build_component(**args())
