#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/create-component.lib.yml", "single_build_component")
#@ load("/lib/fn-args.lib.yml", "mandatory")

#@yaml/text-templated-strings
---
#@ def revng_distributable(name=mandatory, components=mandatory):
configure: |
  mkdir -p "$BUILD_DIR"
install: |
  INSTALLER="$ORCHESTRA_DOTDIR/support/revng-distributable/install.sh"
  echo "659a850e221910a4f20ea8dd0939a31dd9a7e75f92a476ea1cad8bbefb1b6541 $INSTALLER" | \
    sha256sum --quiet -c -
  "$INSTALLER" "(@= name @)" "(@= "\" \"".join(components) @)"
build_dependencies:
  - test/revng-qa
  - #@ template.replace(components)
skip_post_install: true
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-distributable: #@ single_build_component(**revng_distributable("revng", ["revng-c"]))
  revng-distributable-public-demo: #@ single_build_component(**revng_distributable("revng-public-demo", ["revng-c", "toolchain/host/gcc"]))
