#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-development:
    builds:
      default:
        dependencies:
          - revng-c
        configure: mkdir -p "$BUILD_DIR"
        install: echo "Nothing to do"
