#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("/lib/create_component.lib.yml", "single_build_component")

---
#@ def distributable_components():
- revng-c
#@ end

#@yaml/text-templated-strings
---
#@ def revng_distributable():
binary_archives: private
configure: |
  mkdir -p "$BUILD_DIR"
install: |
  INSTALLER="$ORCHESTRA_DOTDIR/support/revng-distributable/install.sh"
  echo "9066b734aa312283762773c30b35a7f0d6b386a65dc5fc16b0866b68889f16a7 $INSTALLER" | \
    sha256sum --quiet -c -
  "$INSTALLER" (@= " ".join(distributable_components()) @)
build_dependencies:
  - test/revng-qa
  - #@ template.replace(distributable_components())
skip_post_install: true
#@ end

#@overlay/match by=overlay.all, expects=1
#@overlay/match-child-defaults missing_ok=True
---
components:
  revng-distributable: #@ single_build_component(**revng_distributable())
